#! /bin/bash
TEMP=25
HUMD=25
SMOKE='False'
XLOCATION=55.55
YLOCATION=55.55
sqlite3 $DataBase "INSERT INTO measuredData(TEMP,HUMD,SMOKE,XLOCATION,YLOCATION) VALUES $($TEMP $HUMD '$SMOKE' $XLOCATION $YLOCATION)"


